### ISSUE TITLE
What should be the selection "Custom set of ad technology providers" with no impact on Revenue?

### ISSUE THREAD

**Issue by yccheok** [googleads/googleads-consent-sdk-android#68]
I notice that in order to display consent form, we need to select "Custom set of ad technology providers"

<img width="571" alt="how to choose 12 ads providers" src="https://user-images.githubusercontent.com/308276/41087242-bcb8167a-6a6e-11e8-90b9-436548ee75e2.png">

But, there's no guideline on this on how should we choose the 12 ads providers?

1) How can we choose the 12 ads providers, without affecting revenue from EU?

2) Will selecting "Custom set of ad technology providers", affect revenue from Non-EU?

Thank you.

**Comment by GuanacoDevs** [comment]
I'm in the same boat, until I learn the proper way to select a Ad Technology Provider, this is what I have come up with.

Check on your Adsense Account, go to Performance Reports>Advanced Reports>Ad Networks and you will see All the Ad Technologies providers that your app has gotten Ads from, that should give you an idea of which Ad providers would be good for you.

If your app is new and don't have any data, I would suggest to go only with Google(default).

In my particular case, my app has been up for 8 months with 450 installs and 45 active installs.

Google Networks reports a 91.5% on impresions and 97.3% on Estimated Earnings.

IMO having Google as only one provider will look better when the user wants to see who the app shares information with, instead of having a list of 12 of which never heard of. In the beginning I thought on choosing the best 12, but by the numbers it doesn't make much of a sense and chose to stick with Google alone.

DISCLAIMER: I know nothing regarding Ad Networks and I chose only Google because of my Admob history and nothing else, sure your situation might be different.

**Comment by rampara** [comment]
This issue tracker is strictly for feature requests and bug reports for the Consent SDK. For other discussion regarding the Consent SDK, I would recommend you reach on the [AdMob Product Support Forum](https://productforums.google.com/forum/#!forum/google-admob-help-forum).
